services:
  - type: web
    name: pasen-dingspelerberg
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pasen-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_TOKEN
        value: pasen2026admin

databases:
  - name: pasen-db
    databaseName: pasen
    plan: free
